### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ineeee** [0XE4/0XE4.github.io#1]
dead: https://github.com/0XE4/0XE4.github.io/blob/master/startpages/Home-cfrank/j/view.js#L41
point to alternative pls https://pomf.cat/

**Comment by 0XE4** [comment]
Thanks for flagging this, I think I will leave the original code as it is unless it's a UI issue or something I messed up when moving it to the Emporium. Anyone who wants to use the page will most likely put their own links in. Plus, it's a good first exercise for people learning to write them :)
