### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by vereis** [0XE4/0XE4.github.io#4]
Check out jsh on my git, what do you think of that?

**Comment by 0XE4** [comment]
Wow, that's very cool @Vyris , it's got quite a few commands. Are you planning to incorporate it into a startpage or something similar?

**Comment by Vyris** [comment]
I'm currently using it as a startpage :) All the commands are in /bin and
thus it's easy to add new commands on the fly so its pretty modular. I've
seen tonnes of Shell Lookalike startpages so I thought I'd share my own is
all.

On 23 February 2016 at 09:31, Mathias Busto <notifications@github.com>
wrote:

> Wow, that's very cool @Vyris <https://github.com/Vyris> , it's got quite
> a few commands. Are you planning to incorporate it into a startpage or
> something similar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0XE4/0XE4.github.io/issues/4#issuecomment-187620678>.
>



-- 
Chris Bailey
Student at the University of Kent
Co-Founder & Lead Programmer at !Crane

**Comment by 0XE4** [comment]
Okay @Vyris I'll add it to the Emporium on the next commit!
